spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DatabaseName
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: bankease.banking@gmail.com
    password: dtniqxynzflcckoz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security: debug

server:
  address: 172.16.96.113

